# See https://linuxcontainers.org/incus/docs/main/howto/initialize/#configuration-format

# Daemon settings
config:
  core.https_address: 192.0.2.1:9999
  images.auto_update_interval: 6

# # Storage pools
# storage_pools:
#   - name: data
#     driver: zfs
#     config:
#       source: my-zfs-pool/my-zfs-dataset

# # Storage volumes
# storage_volumes:
#   - name: my-vol
#     pool: data

# Network devices
networks:
  - name: incus-my-bridge
    type: bridge
    config:
      ipv4.address: auto
      ipv6.address: none

# # Profiles
# profiles:
#   - name: default
#     devices:
#       root:
#         path: /
#         pool: data
#         type: disk
#   - name: test-profile
#     description: "Test profile"
#     config:
#       limits.memory: 2GiB
#     devices:
#       test0:
#         name: test0
#         nictype: bridged
#         parent: incus-my-bridge
#         type: nic
      